[project]
name = "2d-mikasa-consolidation-theory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "mlx>=0.0.1",
    "tqdm>=4.67.1",
]
